travis:
  secure:
    BINSTAR_TOKEN: A8uZbBai8Vm0ji2t3ybqZr0ON8c0AyNzV5mljlRBGYa7N1LcFQ21C9YxHb9ABRn/MQgfMCLC/72rHxvefpQdSip3QUYWSnBlNo41hEdbkYeyJMR0QJx7pGpknUoXROGClKAg6kjtNa2VY+QI+HxXuPxERaKtFIGAxbUhRzGpK2/yoxqcHLtrGgD6isV+2fiDenyVInJ1GTbo+7RQY1wk9GtEs50eauoUeQUB9gcdELbax/Uy3D4qeDB2U28+9OabbveSBTGtxy6WZGg57NPS5Qv8NhMC4d6w/sy3IuC9LBmqvNhD1i/IukjR3q+VOXw2arlPxwx2fzQ4VpIJpy2O09stSAqM0J9eGUbwByYQ/RyqB75KROv1D0a8XDTLL3RDISytIey/YPEbwJ291B12g754SNQEhT7RYkAUodehiyWGPSVYoMZvTNVkUM9TExIWvNdjaFiyPOIEPQRngYHAfl8s/vqj78vuq8LoriE6nkx5LPzk/FG4qNtNt82xsJf3tNCUXg0vjhzN8SN+yBWJr6wsSQnhbbf1nI6Jqq3LidISMwKE6kO94751fuLbx542lQpOzg6Mlt9BpDAk1xgN6YoRGxYoRSWGTEXq7ZBIssKZduy/krfNKwWlErC0rZt4b1dinYU/m3xdZtZ0q2GIWa15aqiZUx+xV0l/JdnPyaA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
