travis:
  secure:
    BINSTAR_TOKEN: wVyBwAGe1ds+pOssF2L38Ryt6tE1BlTZtMG6JHZJzkUPddplcUAZMFfea6w7hbUvJgQAT68xYUMMqXy+2hFwEAt8cXa2Yh7BNzsg3QhTHVxVwnt2E+5dAv4k6a5/hm1iVtusfRG8uIsYCYeHnkn2XzFKhsWBw0rgqX3u+iRjcgP4RvWl2io9+4029NM+PJ0LCMD315pMqZy7CG3EGKPe700fkESd4a1NrxWDzJ6oYbyn7sk+xXQa4OAtzqCotDsHVrU9hOptndvkvfS7opFAMTDHPjm63ORs7pe1Yjd6RSSqigmgV/GyZlHdOF45L9dLm3eR40HsRnmhGvw2SgJ997NUmB+HcqTywbo684u2/OO+zSWG1En+SOZlNkkVI8OvTosgs20zNRELFAnSupOEdjkmC2ruTwT2Sp1dO7eGkdY9TVxHa2jW3ONF9Vxm6j6jn4ozghLqivdDXAIkwpVX9nJcu/iPCG+0UpPg0BmUsFVvbplM5b97ihLjaXprQI2N3avv14RbmUqIGAKpLoyC3N3NRh+AbPe9YsWO+dWJmX3KY1xY9ki/Z59N3Vjz+JDEsalRGZp1FV2kRIFnMmsIIkOp1k8+1hBU949jAl4B21aJVj5gziQP9pojsV5o0LUNh0nwJdvW1XfobOaVglakcX5U5PL0PTN4lpLYzs+12Es=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
